on: [push]

jobs:
  build_container:
    # TODO what host are available? How to test on multiple platforms?
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          load: true
          build-args: |
            LUA_INSTALL_VERSION=5.3.6
            LUAROCKS_INSTALL_VERSION=3.8.0
          # push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myimage
          path: /tmp/myimage.tar

# TODO: Check if there is an easier way!
  test_docker_image:
    runs-on: ubuntu-latest
    needs: build_container
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
          docker exec -it myimage:latest echo -e "Version: \n $(lua -v) - $(luarocks --version)"

        